In [13]:
import numpy as np  #Arrays ko create karne k leye numpy chaheaye

**NUMPY INDEXING AND SLICING OF VECTORS**

In [ ]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [15]:
arr[9]

np.int64(20)

In [16]:
arr_slice = arr[3::2]
arr_slice

array([14, 16, 18, 20])

In [18]:
arr[2:5]

array([13, 14, 15])

In [19]:
arr[4]

np.int64(15)

**NUMPY INDEXING AND SLICING OF MATRIX**

In [ ]:
arr = np.arange(1,31).reshape(6,5) 
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [21]:
arr[1] # Indexing on rows

array([ 6,  7,  8,  9, 10])

In [22]:
arr[0,0]

np.int64(1)

In [23]:
arr[1][2]

np.int64(8)

In [24]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [25]:
slice = arr[3:,3:]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [26]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

**BOOLEAN INDEXING**

In [27]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [28]:
bool_index = arr %2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [29]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])